# Generated by Django 3.2.3 on 2021-06-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('cast', models.CharField(max_length=500)),
                ('year', models.IntegerField(default=2021)),
                ('genre', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=500)),
                ('movie', models.CharField(max_length=500)),
            ],
        ),
    ]
