# Generated by Django 3.2.3 on 2021-06-30 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_movie_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('cast', models.CharField(max_length=500)),
                ('year', models.IntegerField(default=2021)),
                ('genre', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('videoLink', models.CharField(max_length=500)),
                ('tvSeries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tvseries')),
            ],
        ),
    ]
